meta:
  engine: 4.1.0
units:
  ux: 17
  uy: 17
  p: 0.5
  kx: ux + p
  ky: uy + p
  pitch: 2.54
  mcu_width: 17.78
  mcu_height: 33.02
  mcu_padding: 2
  switch_length: 7.3
  pinky_stagger: 5ky/4
  pinky_splay: 5
  ring_splay: 3
  thumb_distance: 14 
  reachy_splay: 5
points:
  rotate: pinky_splay + ring_splay
  key:
    width: ux
    height: uy
    spread: kx
    padding: ky
    autobind: 0
  zones:
    matrix:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky:
        ring.key:
          stagger: pinky_stagger
          splay: -pinky_splay
          origin: [-kx/2, -ky/2]      
        middle.key:
          stagger: ky/4
          splay: -ring_splay
          origin: [-kx/2, -ky/2]
        index.key.stagger: -ky/4
        inner.key.stagger: -ky/2
        pinky.rows:
          top.net: "P2"
          top.reversed_net: "P5"
          home.net: "P3"
          home.reversed_net: "P6"
          bottom.skip: true
        ring.rows:
          top.net: "P21"
          top.reversed_net: "P18"
          home.net: "P15"
          home.reversed_net: "P10"
          bottom.net: "P4"
          bottom.reversed_net: "P4"
        middle.rows:
          top.net: "P20"
          top.reversed_net: "P19"
          home.net: "P14"
          home.reversed_net: "P16"
          bottom.net: "P5"
          bottom.reversed_net: "P3"
        index.rows:
          top.net: "P19"
          top.reversed_net: "P20"
          home.net: "P16"
          home.reversed_net: "P14"
          bottom.net: "P6"
          bottom.reversed_net: "P2"
        inner.rows:
          bottom.skip: true
          top.net: "P18"
          top.reversed_net: "P21"
          home.net: "P10"
          home.reversed_net: "P15"
        pinky.rows.top.bind: [0, kx, 0, 0]
        ring.key.bind: [0, kx, 0, 0]
        ring.rows.bottom.bind: [0, kx, 0, kx/2]
        index.rows.bottom.bind: [0, 0, 0, kx]
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -thumb_distance]
      columns:
        tucky:
        reachy.key:
          stagger: 0
          splay: -5
          origin: [-kx/2, -ky/2]
        tucky.key.net: "P7"
        tucky.key.reversed_net: "P7"
        reachy.key.net: "P8"
        reachy.key.reversed_net: "P8"
        tucky.key.bind: [2u, u/2, 0, 0]
    mcu:
      anchor:
        ref: matrix_inner_home
        shift: [ux/2 + mcu_width/2 + mcu_padding, 3uy/2 - mcu_height/2 + p]
      key:
        width: mcu_width
        height: mcu_height
        bind: [0, 0, ky, kx]
    battery:
      anchor:
        ref: mcu
        shift: [-switch_length/2, 6pitch]
      key:
        width: 5
        height: 5
      columns:
        pos:
        neg.key.spread: switch_length
        pos.key.net: "LIVE"
        pos.key.reversed_net: "B+"
        neg.key.net: "B-"
        neg.key.reversed_net: "LIVE"
    switch:
      anchor:
        ref: mcu
        shift: [0, 4pitch]
        rotate: 180
      key:
        width: 7.85
        height: 2.7
    mounthole_left.anchor:
      - aggregate.parts: [thumb_tucky, matrix_inner_home]
    mounthole_right.anchor:
      - ref: mounthole_left
        shift: [ux/2 + mcu_width/2 + mcu_padding, 0]
outlines:
  mounthole:
    - what: rectangle
      size: [2.2, 2.2]
      where:
        - /mounthole/
  keys:
    - what: rectangle
      size: [ux, uy]
      where:
        - /matrix/
        - /thumb/
      operation: stack
  board:
    - what: rectangle
      size: [ux, uy]
      where:
        - /matrix/
        - /thumb/
      bound: true
    - what: rectangle
      size: [mcu_width, mcu_height]
      where: mcu
      bound: true
    - what: rectangle
      size: [ux, 2uy]
      where: thumb_reachy
      adjust.shift: [ux, uy/2]
      operation: subtract
      expand: 2.5
      joints: 2
pcbs:
  hummingbird:
    template: kicad8
    outlines:
      main:
        outline: board
      keys:
        outline: keys
        layer: Dwgs.User
      mounthole:
        outline: mounthole
        layer: Dwgs.User
    footprints:
      switches:
        what: choc
        where: /thumb/
        params:
          from: GND
          to: "{{net}}"
          keycaps: false
          hotswap: true
      rotated_switches:
        what: choc
        where: /matrix/
        adjust.rotate: 180
        params:
          from: GND
          to: "{{net}}"
          keycaps: false
          hotswap: true
      reversed_switches:
        what: choc
        where: /thumb/
        params:
          from: GND
          to: "{{reversed_net}}"
          keycaps: false
          hotswap: true
          reverse: true
      rotated_reversed_switches:
        what: choc
        where: /matrix/
        adjust.rotate: 180
        params:
          from: GND
          to: "{{reversed_net}}"
          keycaps: false
          hotswap: true
          reverse: true
      mcu:
        what: nicenano
        where: mcu
        adjust.rotate: 270
        params:
          orientation: down
          RAW: ""
          GND: ""
          RST: ""
          VCC: ""
          P1: ""
          P0: ""
      battery:
        what: ufl
        where: /battery/
        params:
          SIG: "{{net}}"
      reversed_battery:
        what: ufl
        where: /battery/
        params:
          SIG: "{{reversed_net}}"
          reverse: true
      switch:
        what: switch
        where: /switch/
        params:
          left: B+
          right: ""
          common: LIVE
          reverse: true
      reversed_switch:
        what: switch
        where: /switch/
        params:
          left: B-
          right: ""
          common: LIVE
      switch_via:
        what: via
        where: /switch/
        adjust.shift: [0, 1.5 - 2pitch]
        params.net: LIVE 
      mounthole:
          what: mounthole
          where: /mounthole/
