meta:
  engine: 4.1.0
units:
  u: 16.5
  mcu_width: 17.78
  mcu_height: 33.02
  battery_pad: 5
  pinky_stagger: 5u/4
  pinky_splay: 5
  ring_splay: 3
  thumb_distance: 14 
  reachy_splay: 5
points:
  rotate: pinky_splay + ring_splay
  key:
    width: u
    height: u
    autobind: 0
  zones:
    matrix:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky.rows.bottom.skip: true
        ring.key:
          stagger: pinky_stagger
          splay: -pinky_splay
          origin: [-u/2, -u/2]
        middle.key:
          stagger: u/4
          splay: -ring_splay
          origin: [-u/2, -u/2]
        index.key.stagger: -u/4
        inner.key.stagger: -u/2
        inner.rows.bottom.skip: true
        pinky.rows.top.bind: [0, u, 0, 0]
        ring.key.bind: [0, u, 0, 0]
        ring.rows.bottom.bind: [0, u, 0, u/2]
        index.rows.bottom.bind: [0, 0, 0, u]
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -thumb_distance]
      columns:
        tucky:
        reachy.key:
          stagger: 0
          splay: -5
          origin: [-u/2, -u/2]
        tucky.key.bind: [2u, u/2, 0, 0]
    mcu:
      anchor:
        ref: matrix_inner_home
        shift: [u/2 + mcu_width/2 + 1.3, 3/2u - mcu_height/2]
      key:
        width: mcu_width
        height: mcu_height
        bind: [0, 0, u, u]
    battery:
      anchor:
        ref: mcu
        shift: [-mcu_width/2 + battery_pad, mcu_height/2 - 1.3]
      key:
        width: 5
        height: 5
      columns:
        pos:
        neg.key.spread: mcu_width - 2battery_pad 
outlines:
  keys:
    - what: rectangle
      size: u
      where:
        - /matrix/
        - /thumb/
      operation: stack
  board:
    - what: rectangle
      size: u
      where:
        - /matrix/
        - /thumb/
      bound: true
    - what: rectangle
      size: [mcu_width, mcu_height]
      where: mcu
      bound: true
    - what: rectangle
      size: [u, 2u]
      where: thumb_reachy
      adjust.shift: [u, u/2]
      operation: subtract
      expand: 2
      joints: 2
pcbs:
  hummingbird:
    template: kicad8
    outlines:
      main:
        outline: board
      keys:
        outline: keys
        layer: Dwgs.User
    footprints:
      switches:
        what: choc
        where: /thumb/
        params:
          from: GND
          to: "{{name}}"
          keycaps: false
          hotswap: true
      rotated_switches:
        what: choc
        where: /matrix/
        adjust.rotate: 180
        params:
          from: GND
          to: "{{name}}"
          keycaps: false
          hotswap: true
      mcu:
        what: nicenano
        where: mcu
        adjust.rotate: 270
        params:
          BP: battery_pos
          BN: battery_neg
          P21: matrix_ring_top
          P20: matrix_middle_top
          P19: matrix_index_top
          P18: matrix_inner_top
          P15: matrix_ring_home
          P14: matrix_middle_home
          P16: matrix_index_home
          P10: matrix_inner_home
          P2: matrix_pinky_top
          P3: matrix_pinky_home
          P4: matrix_ring_bottom
          P5: matrix_middle_bottom
          P6: matrix_index_bottom
          P7: thumb_tucky
          P8: thumb_reachy
      battery:
        what: ufl
        where: /battery/
        params:
          SIG: "{{name}}"
